Repository nextcloud-libraries/nextcloud-vue-collections, pull requests merged in 2024-06, with the labels that each got.

#1227 chore(deps): install nextcloud/l10n, update stylelint dependencies
  package-lock.json
  package.json
  src/components/CollectionList.vue
  src/components/CollectionListItem.vue
Labels: bug, dependencies, 3. to review

#1228 chore: Add SPDX headers and REUSE CI workflow
  .editorconfig
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/reuse.yml
  .gitignore
  .npmignore
  .reuse/dep5
  AUTHORS.md
  LICENSE
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  package-lock.json
  package.json
  src/collectionservice.js
  src/collectionstore.js
  src/components/CollectionList.vue
  src/components/CollectionListItem.vue
  src/index.js
  vite.config.mts
Labels: 3. to review

#1233 chore: Add NPM publish workflow
  .github/workflows/npm-publish.yml
Labels: 3. to review, backport-request

#1224 [vue3]: migrate package to Vue 3
  .eslintrc.js
  package-lock.json
  package.json
  src/collectionstore.js
  src/components/CollectionList.vue
  src/components/CollectionListItem.vue
Labels: dependencies, breaking, 3. to review
